@echo off
echo Starting PhysioResearch Agent...
call .venv\Scripts\activate.bat
echo Installing/updating dependencies...
pip install -r requirements.txt
echo Starting the application...
streamlit run app.py
pause 